di_settings.settings_form:  
  title: 'Digital Initiatives (DI) Settings'  
  route_name: di_settings.settings_form  
  description: 'Configuration Settings for the suite of Digital Initiatives (DI) Modules'  
  parent: system.admin_config_system  
  weight: 99  
