cdn_provider: ''
fluid_container: 1
_core:
  default_config_hash: K8D8uDcrjcfmNP9HbUwIRq_utBuLuypv-8qnZTcVdNM
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://d8digitalstlawu.lndo.site/themes/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  di_stlawu: 8000
