cdn_provider: ''
fluid_container: 1
_core:
  default_config_hash: K8D8uDcrjcfmNP9HbUwIRq_utBuLuypv-8qnZTcVdNM
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://d8digitalstlawu.lndo.site/themes/custom/di_stlawu/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  di_stlawu: 8000
region_wells:
  navigation: ''
  navigation_collapsible: ''
  navigation_utility: ''
  breadcrumbs: ''
  header: ''
  highlighted: ''
  help: ''
  before_content: ''
  page_title: ''
  local_tasks: ''
  content: ''
  after_content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer_top: ''
  footer_first: ''
  footer_second: ''
  footer_third: ''
  footer_fourth: ''
  footer_fifth: ''
table_responsive: '-1'
table: ''
logo:
  path: ''
  url: ''
  use_default: false
breadcrumb: '2'
breadcrumb_title: 0
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
